### ISSUE TITLE
Recognize end screen

### ISSUE THREAD

**Issue by rjbell4** [andrewda/frc-livescore#19]
I'm using frc-livescore to determine the start and end points in a captured Twitch stream, so that I can automatically extra the match video.  I'd really like to include the end score as well in the video.

Do you think that it would be possible to also support the screen like the one I've attached below?
![frame](https://user-images.githubusercontent.com/375968/39451201-d3da85f4-4c9b-11e8-8d1b-b71d48ac38cf.png)

For my own uses, it would suffice just to identify if the frame is like the linked one or not.  However, I can see value in actually parsing the data.  For example, if there's another situation like Week 1, where (at least in the New England District) final scores were not being posted, parsing the data from the end screen could serve as a interim data source, until FIRST provided an initial match update (for Week 1 in NE, it wasn't until about Week 2, at least!)

**Comment by andrewda** [comment]
Yep, that's on the TODO list and can probably get done during the off-season. I'm gonna close this in favor of #2 but feel free to discuss more there!
